Repository Team-Detto/Detto, pull requests merged in 2023-02, with the labels that each got.

#28 [feat] 로그인/회원가입 모달창 UI - 스크롤 방지 기능 개선
  src/components/login/LoginModal.tsx
  src/utils/modal.ts
Labels: enhancement

#37 [feat] 보낸쪽지함/ 받은쪽지함 UI 구현
  src/components/Header.tsx
  src/components/popup/Message.tsx
  src/components/popup/NoteBox.tsx
  src/components/popup/NoteMessage.tsx
  src/components/popup/NotificationBox.tsx
  src/components/popup/NotificationMessage.tsx
  src/components/popup/PopupContainer.tsx
  src/components/popup/styles.tsx
  src/utils/modal.ts
Labels: enhancement

#47 [feat] 마이페이지 유저 정보 조회 추가
  src/apis/mypageUsers.ts
  src/components/Header.tsx
  src/components/common/ProjectItem.tsx
  src/components/common/ProjectList.tsx
  src/components/common/SkillButton.tsx
  src/components/mypage/CareerRadioInput.tsx
  src/components/mypage/Careers.tsx
  src/components/mypage/CheckboxButton.tsx
  src/components/mypage/MyPageInfo.tsx
  src/components/mypage/MyPageProfileImage.tsx
  src/components/mypage/PositionCheckBox.tsx
  src/components/mypage/SkillList.tsx
  src/pages/MyPage.tsx
  src/pages/PublicProfilePage.tsx
  src/react-app-env.d.ts
  src/utils/positions.ts
Labels: enhancement

#49 [feat] 로그인/회원가입 페이지 Navigator, ConfirmButton 추가
  src/assets/styles/colors.ts
  src/components/Header.tsx
  src/components/login/ConfirmButton.tsx
  src/components/login/LoginModal.tsx
  src/components/login/LoginPage0.tsx
  src/components/login/LoginPage1.tsx
  src/components/login/LoginPage2.tsx
  src/components/login/LoginPage3.tsx
  src/components/login/LoginPage4.tsx
  src/components/login/Navigator.tsx
  src/hooks/index.ts
  src/hooks/useGlobalModal.ts
  src/recoil/atoms.ts
Labels: enhancement

#53 [feat] 마이페이지 프로필 이미지 수정, 삭제 기능 추가
  src/apis/mypageUsers.ts
  src/components/mypage/CareerRadioInput.tsx
  src/components/mypage/Careers.tsx
  src/components/mypage/MyPageInfo.tsx
  src/components/mypage/MyPageProfileImage.tsx
  src/hooks/useProfileImage.ts
  src/pages/MyPage.tsx
Labels: enhancement

#55 [PR] Fixes Issue #46
  src/apis/getPost.ts
  src/apis/postDetail.ts
  src/components/projectDetail/WriterToShareArea.tsx
  src/pages/ProjectDetailPage.tsx
Labels: enhancement

#62 [fix] 스크롤 에러 수정
  src/components/ModalContainer.tsx
  src/components/login/LoginModal.tsx
  src/components/popup/NoteModal.tsx
Labels: bug

#65 [feat] GitHub, Google 소셜 로그인 기능 추가
  src/App.tsx
  src/components/login/LoginPage0.tsx
  src/hooks/useSocialLogin.ts
Labels: enhancement

#69 [feat] 마이페이지 유저 정보 수정 추가
  src/apis/getPost.ts
  src/apis/mypageUsers.ts
  src/components/common/SkillButton.tsx
  src/components/findproject/FindProjectHeader.tsx
  src/components/mypage/CareerRadioInput.tsx
  src/components/mypage/Careers.tsx
  src/components/mypage/CheckboxButton.tsx
  src/components/mypage/MyPageInfo.tsx
  src/components/mypage/MyPageProfileImage.tsx
  src/components/mypage/NicknameInput.tsx
  src/components/mypage/PositionCheckBox.tsx
  src/components/mypage/SkillList.tsx
  src/hooks/index.ts
  src/hooks/useProfileImage.ts
  src/hooks/useUpdateProfile.ts
  src/types/mypage/userInfo.ts
  src/utils/positions.ts
  src/utils/validation.ts
Labels: enhancement

#70 [feat] Facebook 소셜 로그인 기능 추가
  src/assets/images/login_facebook.png
  src/assets/images/login_kakao.png
  src/components/ModalContainer.tsx
  src/components/login/LoginPage0.tsx
  src/hooks/useSocialLogin.ts
Labels: enhancement

#71 [feat] 회원가입 시 Firebase 사용자 컬렉션 초기화
  src/hooks/useSocialLogin.ts
Labels: enhancement

#77 [fix] 마이페이지 기술스택 수정 부분 개선
  src/apis/mypageUsers.ts
  src/components/mypage/CareerRadioInput.tsx
  src/components/mypage/Careers.tsx
  src/components/mypage/CheckboxButton.tsx
  src/components/mypage/MyPageInfo.tsx
  src/components/mypage/PositionCheckBox.tsx
  src/components/mypage/SkillList.tsx
  src/hooks/useUpdateProfile.ts
  src/pages/MyPage.tsx
Labels: bug

#81 [feat] useAuth 커스텀훅 추가
  src/hooks/index.ts
  src/hooks/useAuth.ts
Labels: enhancement

#82 [fix] useAuth 반환 타입 수정
  src/hooks/useAuth.ts
Labels: bug

#83 [fix] 헤더 내비게이션 로그인 여부 반영
  src/assets/styles/globalStyled.ts
  src/components/Header.tsx
  src/hooks/index.ts
  src/hooks/useHeader.ts
Labels: enhancement

#86 [feat] 회원가입 기능 구현
  src/components/common/SkillButton.tsx
  src/components/login/LoginModal.tsx
  src/components/login/LoginPage1.tsx
  src/components/login/LoginPage3.tsx
  src/components/login/Navigator.tsx
  src/components/login/SetPositions.tsx
  src/components/login/SetProfile.tsx
  src/components/login/SetSkills.tsx
  src/components/login/SetSkillsPageStack.tsx
  src/components/login/SocialLogin.tsx
  src/components/login/Welcome.tsx
  src/components/login/index.ts
  src/hooks/useAuth.ts
  src/hooks/useSocialLogin.ts
Labels: enhancement

#88 [fix] 마이페이지 UI 변경
  src/assets/styles/globalStyled.ts
  src/components/mypage/CareerRadioInput.tsx
  src/components/mypage/CheckboxButton.tsx
  src/components/mypage/LeftTab.tsx
  src/components/mypage/MyPageInfo.tsx
  src/components/mypage/MyPageProfileImage.tsx
  src/components/mypage/TextInput.tsx
  src/pages/MyPage.tsx
Labels: enhancement

#89 [feat] 페이지 이동 시 알림/쪽지 팝업창 닫기 기능 추가
  src/components/Header.tsx
  src/hooks/usePopup.ts
Labels: enhancement

#91 [fix] 마이페이지 UI 수정
  src/components/mypage/LeftTab.tsx
  src/components/mypage/MyPageProfileImage.tsx
  src/pages/MyPage.tsx
Labels: bug

#94 [feat] 프로젝트 찾기 UI 변경 및 토글 버튼 과 카테고리 필터 기능
  src/apis/boardService.ts
  src/components/ContentCard.tsx
  src/components/editpage/EditPageStack.tsx
  src/components/findproject/FindProjectHeader.tsx
  src/components/findproject/FindProjectList.tsx
  src/components/main/recommendation/MainRecommendation.tsx
  src/components/writepage/WritePageStack.tsx
  src/hooks/index.ts
  src/hooks/useFindProject.ts
  src/hooks/useWrite.ts
  src/pages/FindProjectPage.tsx
  src/types/write/writeType.ts
  src/utils/validation.ts
Labels: enhancement

#95 [PR] 지원자 목록 데이터 구조 변경
  src/apis/postDetail.ts
  src/components/projectDetail/ApplicantListArea.tsx
  src/components/projectDetail/ApplyButtonArea.tsx
  src/components/projectDetail/WriterToShareArea.tsx
  src/components/projectDetail/modals/ApplyModal.tsx
  src/components/projectDetail/modals/InviteModal.tsx
  src/pages/ProjectDetailPage.tsx
Labels: enhancement

#96 [feat] 쪽지 모달창 네비게이터 추가
  src/components/common/ModalNavigator.tsx
  src/components/login/SetPositions.tsx
  src/components/login/SetProfile.tsx
  src/components/login/SetSkills.tsx
  src/components/login/SocialLogin.tsx
  src/components/popup/NoteBox.tsx
  src/components/popup/NoteModal.tsx
  src/components/popup/NotificationBox.tsx
Labels: enhancement

#97 [feat] 프로필 수정 모달 추가
  src/components/common/ConfirmAlert.tsx
  src/components/mypage/MyPageInfo.tsx
  src/components/mypage/MyPageProfileImage.tsx
  src/components/mypage/ProfileImageModal.tsx
Labels: enhancement

#98 [feat] 회원가입 경력 선택 추가, 프로필 사진 변경 버튼 수정
  src/components/login/SetPositions.tsx
  src/components/login/SetProfile.tsx
Labels: enhancement

#99 [feat] 메인 페이지 Tap 기능
  src/components/main/Calendar/MainCalendar.tsx
  src/components/main/Calendar/ProjectCalendar.tsx
  src/components/main/Calendar/ProjectDetail.tsx
  src/components/main/Calendar/ProjectList.tsx
  src/components/main/findUsers/MainFindUsers.tsx
  src/components/main/recommendation/MainRecommendation.tsx
Labels: enhancement

#101 [feat] 쪽지함 조회, 쪽지 쓰기 기능 구현
  .pnp.cjs
  .yarn/cache/@types-uuid-npm-9.0.0-979023c16f-59ae56d954.zip
  .yarn/cache/uuid-npm-9.0.0-46c41e3e43-8dd2c83c43.zip
  package.json
  src/apis/note.ts
  src/components/Header.tsx
  src/components/common/modal/ModalContainer.tsx
  src/components/common/modal/ModalNavigator.tsx
  src/components/common/modal/modal.ts
  src/components/login/SetPositions.tsx
  src/components/login/SetProfile.tsx
  src/components/login/SetSkills.tsx
  src/components/login/SocialLogin.tsx
  src/components/popup/CustomButton.tsx
  src/components/popup/NoteBox.tsx
  src/components/popup/NoteMessage.tsx
  src/components/popup/NoteModal.tsx
  src/components/popup/ReadInboxNote.tsx
  src/components/popup/ReadOutboxNote.tsx
  src/components/popup/SendNote.tsx
  src/components/popup/styles.tsx
  src/hooks/index.ts
  src/hooks/useNote.ts
  src/routes/Router.tsx
  yarn.lock
Labels: enhancement

#106 [feat] 마이페이지 연락처 변경 추가
  src/apis/mypageUsers.ts
  src/components/common/ConfirmAlert.tsx
  src/components/login/SetProfile.tsx
  src/components/mypage/Careers.tsx
  src/components/mypage/MyPageInfo.tsx
  src/components/mypage/MyPageProfileImage.tsx
  src/components/mypage/PositionCheckBox.tsx
  src/components/mypage/SkillList.tsx
  src/components/mypage/TextInput.tsx
  src/hooks/useUpdateProfile.ts
  src/pages/MyPage.tsx
  src/react-app-env.d.ts
  src/types/mypage/userInfo.ts
  src/utils/validation.ts
Labels: enhancement

#108 [feat] 글 작성 & 수정 유효성 검사와 Toast Popup 생성
  src/apis/boardService.ts
  src/components/common/ValidationToastPopup.tsx
  src/components/findproject/FindProjectList.tsx
  src/hooks/index.ts
  src/hooks/useEditBoard.ts
  src/hooks/useFindProject.ts
  src/hooks/useToastPopup.ts
  src/hooks/useWrite.ts
  src/pages/FindProjectPage.tsx
  src/pages/ProjectEditPage.tsx
  src/pages/ProjectWritePage.tsx
  src/types/write/writeType.ts
  src/utils/validation.ts
Labels: enhancement

#109 [PR] 조회수 기능 구현, 좋아요 기능 로직 수정, 상세보기 페이지 오류 수정
  src/apis/findWithCollectionName.ts
  src/apis/postDetail.ts
  src/components/projectDetail/Likes.tsx
  src/components/projectDetail/MemberInfoArea.tsx
  src/components/projectDetail/Share.tsx
  src/components/projectDetail/Views.tsx
  src/components/projectDetail/WriterToShareArea.tsx
  src/components/projectDetail/modals/ApplyModal.tsx
  src/pages/ProjectDetailPage.tsx
Labels: enhancement

#112 [팀원 찾기] 내가 관심 있는 프로젝트만 아이콘 색상처리 및 이 외 처리
  src/apis/boardService.ts
  src/apis/userService.ts
  src/components/ContentCard.tsx
  src/components/findproject/FindProjectList.tsx
  src/components/main/Calendar/ProjectCalendar.tsx
  src/components/main/recommendation/MainRecommendation.tsx
  src/hooks/useFindProject.ts
  src/pages/FindProjectPage.tsx
Labels: enhancement

#114 [feat] 쪽지/알림 조회, 작성, 수정 기능 구현
  .pnp.cjs
  .yarn/cache/@types-uuid-npm-9.0.0-979023c16f-59ae56d954.zip
  .yarn/cache/uuid-npm-9.0.0-46c41e3e43-8dd2c83c43.zip
  package.json
  src/apis/note.ts
  src/apis/notes.ts
  src/apis/notification.ts
  src/apis/notifications.ts
  src/components/Header.tsx
  src/components/login/SetProfile.tsx
  src/components/popup/NoteBox.tsx
  src/components/popup/NoteMessage.tsx
  src/components/popup/NoteModal.tsx
  src/components/popup/NotificationBox.tsx
  src/components/popup/NotificationMessage.tsx
  src/components/popup/ReadInboxNote.tsx
  src/components/popup/ReadOutboxNote.tsx
  src/components/popup/SendNote.tsx
  src/components/popup/styles.tsx
  src/hooks/useNote.ts
  src/hooks/useNotification.ts
  src/hooks/useSocialLogin.ts
  src/react-app-env.d.ts
  src/recoil/atoms.ts
  src/utils/staleTime.ts
  yarn.lock
Labels: enhancement

#115 [fix] 쪽지 보내기 receiverUid 에러 수정
  src/components/popup/SendNote.tsx
Labels: bug

#117 [feat] useNote, useNotification 커스텀훅 개선
  src/components/popup/SendNote.tsx
  src/hooks/index.ts
  src/hooks/useNote.ts
  src/hooks/useNotification.ts
Labels: enhancement

#118 [PR] 프로젝트 지원, 초대 시 데이터베이스에 값 넣기
  src/apis/postDetail.ts
  src/components/projectDetail/ApplicantListArea.tsx
  src/components/projectDetail/ApplyButtonArea.tsx
  src/components/projectDetail/Likes.tsx
  src/components/projectDetail/MemberInfoArea.tsx
  src/components/projectDetail/WriterToShareArea.tsx
  src/components/projectDetail/modals/ApplyModal.tsx
  src/components/projectDetail/modals/InviteModal.tsx
  src/pages/ProjectDetailPage.tsx
Labels: enhancement

#119 [feat] 프로젝트 상세 보기 모집 & 지원 기준확인 및 Alert 생성
  src/apis/postDetail.ts
  src/components/ContentCard.tsx
  src/components/projectDetail/ApplyButtonArea.tsx
  src/hooks/useModal.ts
  src/pages/ProjectDetailPage.tsx
Labels: enhancement

#122 [PR] 프로젝트 상세보기 전반적인 로직 수정
  src/apis/postDetail.ts
  src/components/main/Calendar/ProjectDetail.tsx
  src/components/projectDetail/ApplicantListArea.tsx
  src/components/projectDetail/ApplyButtonArea.tsx
  src/components/projectDetail/Likes.tsx
  src/components/projectDetail/MemberInfoArea.tsx
  src/components/projectDetail/ProjectInfoArea.tsx
  src/components/projectDetail/TitleThumbnailArea.tsx
  src/components/projectDetail/modals/ApplyModal.tsx
  src/components/projectDetail/modals/InviteModal.tsx
  src/hooks/useModal.ts
  src/pages/ProjectDetailPage.tsx
Labels: enhancement

#123 [feat] 쪽지, 알림 유효성검사
  src/components/common/ValidationToastPopup.tsx
  src/components/login/SetPositions.tsx
  src/components/login/SetProfile.tsx
  src/components/login/SetSkills.tsx
  src/components/popup/SendNote.tsx
  src/hooks/useNotification.ts
Labels: enhancement

#124 [feat] 마이페이지 프로젝트 리스트 조회 추가
  src/apis/mypageUsers.ts
  src/assets/images/default_img.jpg
  src/components/common/ProjectList.tsx
  src/components/common/myProjectList/ProjectItem.tsx
  src/components/common/myProjectList/ProjectItemMembers.tsx
  src/components/common/myProjectList/ProjectList.tsx
  src/components/mypage/ProjectsTab.tsx
  src/hooks/index.ts
  src/hooks/useProjectList.ts
  src/pages/MyPage.tsx
  src/pages/PublicProfilePage.tsx
  src/utils/positions.ts
Labels: enhancement

#129 [fix] 자잘한 버그와 피드백 수정
  src/components/editpage/ProjectEditPageBody.tsx
  src/components/editpage/ProjectEditPageFooter.tsx
  src/components/projectDetail/TitleThumbnailArea.tsx
  src/components/writepage/ProjectWritePageBody.tsx
  src/components/writepage/ProjectWritePageFooter.tsx
  src/hooks/useEditBoard.ts
  src/hooks/useWrite.ts
  src/utils/validation.ts
Labels: enhancement

#126 [feat] 메인 페이지 로고 추가, 이미지 최적화
  src/assets/images/VectorDown.png
  src/assets/images/VectorUp.png
  src/assets/images/login_facebook.png
  src/assets/images/login_github.png
  src/assets/images/login_google.png
  src/assets/images/login_key.png
  src/assets/images/login_welcome.png
  src/assets/images/logo_error.png
  src/assets/images/logo_loading.gif
  src/assets/images/logo_loading.png
  src/assets/images/logo_main1.png
  src/assets/images/logo_main2.gif
  src/components/main/banner/MainBanner.tsx
  src/pages/ErrorPage.tsx
  src/pages/LoadingPage.tsx
Labels: enhancement

#130 [feat] 회원 탈퇴 기능 추가
  src/components/mypage/LeftTab.tsx
  src/hooks/useHeader.ts
  src/pages/MyPage.tsx
Labels: enhancement

#133 [feat] 무한 스크롤 적용
  .pnp.cjs
  .yarn/cache/react-bottom-scroll-listener-npm-5.1.0-ba8a25ede4-620af7e9e7.zip
  package.json
  src/apis/boardService.ts
  src/hooks/useFindProject.ts
  yarn.lock
Labels: enhancement

#135 [feat] scroll to top 버튼 추가
  src/assets/images/scroll_to_top.png
  src/components/ScrollToTopButton.tsx
  src/routes/Router.tsx
Labels: enhancement

#136 [feat] 공개프로필 조회 추가
  src/components/ContentCard.tsx
  src/components/common/myProjectList/ProjectItem.tsx
  src/components/mypage/ProjectsTab.tsx
  src/components/projectDetail/MemberInfoArea.tsx
  src/components/publicProfile/UserPositions.tsx
  src/components/publicProfile/UserStacks.tsx
  src/hooks/useProjectList.ts
  src/pages/MyPage.tsx
  src/pages/ProjectDetailPage.tsx
  src/pages/PublicProfilePage.tsx
  src/utils/positions.ts
  src/utils/skills.ts
Labels: enhancement

#140 [feat] 알림창 클릭 시 알림 모두 읽기
  src/components/popup/NotificationBox.tsx
  src/components/popup/NotificationMessage.tsx
  src/components/popup/styles.tsx
Labels: enhancement

#143 [feat] 프로젝트 리스트 데이터 없을 경우 메세지 추가
  src/components/common/myProjectList/ProjectList.tsx
Labels: enhancement

#148 [feat] 메인페이지 렌더링 에러 해결, 조회 기능 추가
  src/apis/getPost.ts
  src/apis/userService.ts
  src/assets/images/VectorDown.png
  src/assets/images/VectorNext.png
  src/assets/images/VectorPrev.png
  src/assets/images/VectorUp.png
  src/assets/images/junior.png
  src/components/main/Calendar/MainCalendar.tsx
  src/components/main/Calendar/ProjectDetail.tsx
  src/components/main/Calendar/ProjectList.tsx
  src/components/main/banner/MainBanner.tsx
  src/components/main/findUsers/FindUserSlider.tsx
  src/components/main/findUsers/MainFindUsers.tsx
  src/components/main/recommendation/MainRecommendation.tsx
  src/recoil/atoms.ts
  src/utils/staleTime.ts
Labels: bug, enhancement

#150 [feat] 이미지 파일 업로드 리사이징
  .pnp.cjs
  .yarn/cache/react-image-file-resizer-npm-0.4.8-6676df75d7-b8f169bc81.zip
  package.json
  src/apis/boardService.ts
  src/apis/imageService.ts
  src/components/editpage/ProjectEditPageBody.tsx
  src/components/editpage/ProjectEditPageHeader.tsx
  src/components/writepage/ProjectWritePageBody.tsx
  src/components/writepage/ProjectWritePageHeader.tsx
  src/hooks/useEditBoard.ts
  src/hooks/useWrite.ts
  yarn.lock
Labels: enhancement

#152 [fix] 마이페이지 경력 수정 외 여러 버그 해결
  src/components/common/SkillButton.tsx
  src/components/login/SetProfile.tsx
  src/components/mypage/CareerRadioInput.tsx
  src/components/mypage/Careers.tsx
  src/components/mypage/MyPageInfo.tsx
  src/components/mypage/MyPageProfileImage.tsx
  src/components/mypage/PositionCheckBox.tsx
  src/components/mypage/ProfileImageModal.tsx
  src/components/mypage/SkillList.tsx
  src/components/mypage/TextInput.tsx
  src/hooks/useUpdateProfile.ts
  src/recoil/atoms.ts
  src/utils/validation.ts
Labels: bug, enhancement

#153 [fix] 스크롤바 여부에 따른 헤더 덜컹거림 현상 수정
  src/assets/styles/globalStyled.ts
Labels: bug

#155 [fix] 팀원 찾기 카드 UI 수정
  src/components/ContentCard.tsx
Labels: enhancement

#157 [fix] 마이페이지, 공개페이지 stale time 적용
  src/components/common/myProjectList/ProjectList.tsx
  src/pages/MyPage.tsx
  src/pages/PublicProfilePage.tsx
  src/utils/staleTime.ts
Labels: enhancement

#162 [fix] 유저 정보 수정 후 버튼 클릭 시의 유효성 검사 확인 추가
  src/components/mypage/MyPageInfo.tsx
  src/components/mypage/UserInfoTop.tsx
  src/hooks/useUpdateProfile.ts
  src/pages/MyPage.tsx
Labels: bug

#163 Featuer/project detail viewer
  src/components/common/modal/ModalContainer.tsx
  src/components/common/myProjectList/ProjectList.tsx
  src/components/popup/SendNote.tsx
  src/components/projectDetail/ApplicantListArea.tsx
  src/components/projectDetail/ContentArea.tsx
  src/components/projectDetail/Likes.tsx
  src/components/projectDetail/WriterToShareArea.tsx
  src/hooks/useProjectList.ts
  src/pages/ProjectDetailPage.tsx
  src/pages/PublicProfilePage.tsx
Labels: bug, enhancement

#167 [Feat] 회원가입 모달 UI 수정
  src/components/login/LoginModal.tsx
  src/components/login/SetPositions.tsx
  src/components/login/SocialLogin.tsx
Labels: enhancement

#168 [fix] 버튼 hover 효과 통일
  src/components/common/Alert.tsx
  src/components/common/ApplyPositionButton.tsx
  src/components/common/ConfirmAlert.tsx
  src/components/common/myProjectList/ProjectsTab.tsx
  src/components/editpage/ProjectEditPageBody.tsx
  src/components/login/ConfirmButton.tsx
  src/components/login/Welcome.tsx
  src/components/main/Calendar/ProjectDetail.tsx
  src/components/main/findUsers/MainFindUsers.tsx
  src/components/main/recommendation/MainRecommendation.tsx
  src/components/mypage/LeftTab.tsx
  src/components/mypage/MyPageInfo.tsx
  src/components/mypage/ProfileImageModal.tsx
  src/components/projectDetail/ApplyButtonArea.tsx
  src/components/projectDetail/modals/ApplyModal.tsx
  src/components/writepage/ProjectWritePageBody.tsx
  src/components/writepage/ProjectWritePageFooter.tsx
  src/pages/MyPage.tsx
  src/pages/PublicProfilePage.tsx
Labels: enhancement

#174 [feat] 알림 보내기 기능 추가
  src/components/popup/NotificationBox.tsx
  src/components/popup/NotificationMessage.tsx
  src/components/projectDetail/ApplyModal/ApplyButtonArea.tsx
  src/components/projectDetail/ApplyModal/ApplyModal.tsx
  src/components/projectDetail/InviteModals/InviteModal.tsx
  src/hooks/useNotification.ts
  src/pages/ProjectDetailPage.tsx
  src/react-app-env.d.ts
Labels: enhancement

#176 [feat] 로그인 권한 예외처리
  src/App.tsx
  src/apis/postDetail.ts
  src/components/Header.tsx
  src/components/projectDetail/ApplyButtonArea.tsx
  src/components/projectDetail/Likes.tsx
  src/hooks/index.ts
  src/hooks/useFindProject.ts
  src/hooks/useIsLogin.ts
  src/pages/PublicProfilePage.tsx
  src/pages/Root.tsx
  src/routes/Router.tsx
  src/utils/modal.ts
Labels: bug, enhancement

#180 [fix] toast ui viewer 렌더링 에러 수정
  src/components/projectDetail/ContentArea.tsx
  src/hooks/useEditBoard.ts
  src/hooks/useWrite.ts
  src/utils/validation.ts
Labels: bug, enhancement

#183 [fix] 썸네일 이미지 업로드 버튼 색상 처리 & 확장자 고정
  src/components/editpage/ProjectEditPageBody.tsx
  src/components/writepage/ProjectWritePageBody.tsx
  src/hooks/useEditBoard.ts
  src/hooks/useWrite.ts
  src/pages/ProjectEditPage.tsx
  src/types/write/writeType.ts
Labels: enhancement

#186 [feat] 쪽지 프로필 이미지 클릭 시 공개프로필로 이동
  src/components/popup/ReadInboxNote.tsx
  src/components/popup/ReadOutboxNote.tsx
  src/components/popup/styles.tsx
  src/utils/modal.ts
Labels: enhancement

#187 [fix] 슬라이더 width 에러 수정
  src/components/main/banner/MainBanner.tsx
Labels: bug

#188 [feat] 알림/쪽지 읽지 않은 메세지 수, 예외처리 문구 추가
  src/components/popup/NoteBox.tsx
  src/components/popup/NotificationBox.tsx
  src/components/popup/styles.tsx
Labels: enhancement

#190 [feat] 공유 기능 추가 및 적용 이 외 작업
  .pnp.cjs
  .yarn/cache/jsonp-npm-0.2.1-de73bd1749-90aabd9deb.zip
  .yarn/cache/react-share-npm-4.4.1-8a10786b66-f86bf7415f.zip
  package.json
  src/components/common/ValidationToastPopup.tsx
  src/components/findproject/FindProjectHeader.tsx
  src/components/findproject/FindProjectList.tsx
  src/components/projectDetail/Share.tsx
  src/components/projectDetail/WriterToShareArea.tsx
  src/pages/ProjectDetailPage.tsx
  yarn.lock
Labels: enhancement

#191 [fix] minor error 수정
  src/apis/boardService.ts
  src/apis/getPost.ts
  src/apis/userService.ts
  src/assets/images/project_member.png
  src/assets/images/project_thumbnail.png
  src/components/ContentCard.tsx
  src/components/common/myProjectList/ProjectList.tsx
  src/components/main/Calendar/ProjectDetail.tsx
  src/components/main/recommendation/MainRecommendation.tsx
  src/components/projectDetail/TitleThumbnailArea.tsx
  src/components/projectDetail/WriterToShareArea.tsx
  src/index.tsx
  src/utils/positions.ts
Labels: bug, enhancement

#194 [fix] 알림 클릭 시 읽음 처리
  src/components/popup/NotificationMessage.tsx
  src/components/popup/styles.tsx
Labels: bug

#195 [PR] 1차 배포 전 수정
  src/components/common/Alert.tsx
  src/components/projectDetail/MemberInfoArea.tsx
  src/hooks/useWrite.ts
  src/pages/ProjectDetailPage.tsx
  src/routes/Router.tsx
Labels: enhancement

#198 [fix] build를 위한 eslintrc 설정 제거
  .eslintrc
Labels: bug

#200 [feat] 헤더 모바일 UI 추가
  src/components/Header.tsx
  src/components/MobileHeader.tsx
  src/hooks/useHeader.ts
Labels: enhancement

#203 [feat] 로그인/회원가입 모바일 UI 추가
  src/assets/images/login_mobile_facebook.png
  src/assets/images/login_mobile_github.png
  src/assets/images/login_mobile_google.png
  src/components/common/modal/ModalNavigator.tsx
  src/components/login/LoginModal.tsx
  src/components/login/index.ts
  src/components/login/mobile/MobileConfirmButton.tsx
  src/components/login/mobile/MobileSetPositions.tsx
  src/components/login/mobile/MobileSetProfile.tsx
  src/components/login/mobile/MobileSetSkills.tsx
  src/components/login/mobile/MobileSetSkillsPageStack.tsx
  src/components/login/mobile/MobileSocialLogin.tsx
  src/components/login/mobile/MobileWelcome.tsx
Labels: enhancement

#204 [feat] 마이페이지 모바일 UI 추가
  src/components/common/myProjectList/ProjectList.tsx
  src/components/common/myProjectList/ProjectsTab.tsx
  src/components/common/myProjectList/mobile/MobileProjectListTab.tsx
  src/components/mypage/LeftTab.tsx
  src/components/mypage/MyPageInfo.tsx
  src/components/mypage/MyPageProfileImage.tsx
  src/components/mypage/ProfileImageModal.tsx
  src/components/mypage/TextInput.tsx
  src/components/mypage/mobile/MobileMyPage.tsx
  src/components/mypage/mobile/MobileProjectList.tsx
  src/components/mypage/mobile/MobileTopTab.tsx
  src/components/mypage/mobile/MobileUserInfo.tsx
  src/hooks/useProjectList.ts
  src/hooks/useUpdateProfile.ts
  src/pages/MyPage.tsx
  src/react-app-env.d.ts
Labels: enhancement

#206 fix: 회원가입 시 쪽지보내기 에러 수정
  src/hooks/useSocialLogin.ts
Labels: bug

#211 [feat] 글 작성 Mobile 적응형 UI 구현
  src/components/common/SkillButton.tsx
  src/components/common/mobile/MobileConfirmAlert.tsx
  src/components/common/mobile/MobileContainer.tsx
  src/components/writepage/ProjectWritePageFooter.tsx
  src/components/writepage/mobile/WritePageMobileBody.tsx
  src/components/writepage/mobile/WritePageMobileDeadline.tsx
  src/components/writepage/mobile/WritePageMobileFooter.tsx
  src/components/writepage/mobile/WritePageMobileHeader.tsx
  src/components/writepage/mobile/WritePageMobilePeriod.tsx
  src/components/writepage/mobile/WritePageMobilePosition.tsx
  src/components/writepage/mobile/WritePageMobileStack.tsx
  src/components/writepage/mobile/WritePageMobileThumbnail.tsx
  src/pages/ProjectWritePage.tsx
Labels: enhancement

#212 [PR] 공개프로필, 프로젝트 상세보기 모바일 UI 구현 1차
  src/components/common/ApplyPositionButton.tsx
  src/components/common/myProjectList/ProjectsTab.tsx
  src/components/mypage/mobile/MobileProjectList.tsx
  src/components/projectDetail/ApplyModal/ApplyButtonArea.tsx
  src/components/projectDetail/ApplyModal/ApplyModal.tsx
  src/components/projectDetail/ApplyModal/ApplyMotiveArea.tsx
  src/components/projectDetail/ApplyModal/ApplyPositonArea.tsx
  src/components/projectDetail/mobile/MobileApplicantCard.tsx
  src/components/projectDetail/mobile/MobileApplicantsList.tsx
  src/components/projectDetail/mobile/MobileApplyButtonArea.tsx
  src/components/projectDetail/mobile/MobileMemberInfoArea.tsx
  src/components/projectDetail/mobile/MobileRecruitContentArea.tsx
  src/components/projectDetail/mobile/MobileTitleThumbnailArea.tsx
  src/components/projectDetail/mobile/MobileViewsToShareArea.tsx
  src/components/projectDetail/mobile/MobileWirterToProjectInfoArea.tsx
  src/components/projectDetail/mobile/MobileWriterToProjectInfoArea.tsx
  src/components/projectDetail/mobile/projectDetailMobile.tsx
  src/components/publicProfile/UserPositions.tsx
  src/components/publicProfile/UserStacks.tsx
  src/components/publicProfile/mobile/MobilePublciProfilePage.tsx
  src/components/publicProfile/mobile/MobilePublicProfilePage.tsx
  src/hooks/useProjectList.ts
  src/pages/ProjectDetailPage.tsx
  src/pages/PublicProfilePage.tsx
  src/utils/skills.ts
Labels: enhancement

#214 [feat] 글 수정 적응형 Mobile UI 작업
  src/components/editpage/mobile/EditPageMobileBody.tsx
  src/components/editpage/mobile/EditPageMobileDeadline.tsx
  src/components/editpage/mobile/EditPageMobileFooter.tsx
  src/components/editpage/mobile/EditPageMobileHeader.tsx
  src/components/editpage/mobile/EditPageMobilePeriod.tsx
  src/components/editpage/mobile/EditPageMobilePosition.tsx
  src/components/editpage/mobile/EditPageMobileStack.tsx
  src/components/editpage/mobile/EditPageMobileThumbnail.tsx
  src/components/writepage/mobile/WritePageMobileBody.tsx
  src/components/writepage/mobile/WritePageMobileFooter.tsx
  src/components/writepage/mobile/WritePageMobileHeader.tsx
  src/hooks/useEditBoard.ts
  src/pages/ProjectEditPage.tsx
  src/pages/ProjectWritePage.tsx
Labels: enhancement

#215 fix: 회원 탈퇴 시 deleteDoc 임시 주석 처리
  src/components/mypage/LeftTab.tsx
Labels: enhancement

#217 [feat] 로그인/회원가입 모바일 UI
  src/assets/images/login_mobile_facebook.png
  src/components/Header.tsx
  src/components/MobileHeader.tsx
  src/components/common/ValidationToastPopup.tsx
  src/components/common/modal/ModalContainer.tsx
  src/components/login/mobile/MobileSetPositions.tsx
  src/components/login/mobile/MobileSetSkillsPageStack.tsx
  src/components/popup/NoteModal.tsx
  src/components/popup/PopupContainer.tsx
  src/components/popup/mobile/MobileCustomButton.tsx
  src/components/popup/mobile/MobileNoteBox.tsx
  src/components/popup/mobile/MobileNotificationBox.tsx
  src/components/popup/mobile/MobileReadInboxNote.tsx
  src/components/popup/mobile/MobileReadOutboxNote.tsx
  src/components/popup/mobile/MobileSendNote.tsx
  src/components/popup/mobile/styles.tsx
  src/hooks/usePopup.ts
Labels: enhancement

#220 [feat] 마이페이지 모바일 UI 추가 작업
  src/components/MobileContentCard.tsx
  src/components/mypage/mobile/MobileMyPage.tsx
  src/components/mypage/mobile/MobileProjectList.tsx
  src/components/mypage/mobile/MobileSkillStackList.tsx
  src/components/mypage/mobile/MobileUserInfo.tsx
  src/components/writepage/mobile/WritePageMobileStack.tsx
Labels: enhancement

#226 [PR] 모바일 초대하기 모달 UI 및 기능 구현
  src/components/common/mobile/MobileAlert.tsx
  src/components/projectDetail/ApplicantCard.tsx
  src/components/projectDetail/ApplicantListArea.tsx
  src/components/projectDetail/ApplyModal/ApplyButtonArea.tsx
  src/components/projectDetail/ApplyModal/ApplyModal.tsx
  src/components/projectDetail/InviteModals/InviteModal.tsx
  src/components/projectDetail/mobile/EndRecruitButton.tsx
  src/components/projectDetail/mobile/MobileApplicantCard.tsx
  src/components/projectDetail/mobile/MobileApplicantsList.tsx
  src/components/projectDetail/mobile/MobileApplyButtonArea.tsx
  src/components/projectDetail/mobile/MobileInviteModal/MobileInviteModal.tsx
  src/components/projectDetail/mobile/MobileTitleThumbnailArea.tsx
  src/components/projectDetail/mobile/projectDetailMobile.tsx
  src/components/publicProfile/UserStacks.tsx
  src/pages/ProjectDetailPage.tsx
Labels: enhancement

#228 [fix] 모바일 마이페이지, 헤더 버그 수정
  src/components/MobileContentCard.tsx
  src/components/MobileHeader.tsx
  src/components/mypage/mobile/MobileUserInfo.tsx
  src/components/popup/mobile/MobileDropdownMenu.tsx
  src/hooks/usePopup.ts
  src/recoil/atoms.ts
Labels: bug

#231 [feat] 모바일 회원가입 UI 수정
  src/components/common/modal/ModalNavigator.tsx
  src/components/login/SetProfile.tsx
  src/components/login/mobile/MobileSetProfile.tsx
  src/components/login/mobile/MobileSetSkillsPageStack.tsx
  src/components/mypage/MyPageProfileImage.tsx
  src/components/mypage/ProfileImageModal.tsx
  src/components/mypage/TextInput.tsx
  src/components/mypage/UserInfoTop.tsx
  src/components/projectDetail/Likes.tsx
  src/components/projectDetail/Share.tsx
Labels: enhancement

#232 [fix] 마이페이지 버그 수정
  src/apis/mypageUsers.ts
  src/components/common/myProjectList/ProjectList.tsx
  src/components/mypage/Careers.tsx
  src/components/mypage/MyPageInfo.tsx
  src/components/mypage/PositionCheckBox.tsx
  src/components/mypage/ProfileImageModal.tsx
  src/components/mypage/mobile/MobileMyPage.tsx
  src/components/mypage/mobile/MobileUserInfo.tsx
  src/hooks/useProfileImage.ts
  src/hooks/useUpdateProfile.ts
  src/pages/MyPage.tsx
  src/react-app-env.d.ts
Labels: bug

#235 [feat] 글 작성 & 수정 Mobile 적응형 UI 작업 및 기능 추가 작업
  src/components/common/LabelInput.tsx
  src/components/editpage/mobile/EditPageMobileBody.tsx
  src/components/editpage/mobile/EditPageMobileFooter.tsx
  src/components/editpage/mobile/EditPageMobilePosition.tsx
  src/components/editpage/mobile/EditPageMobileThumbnail.tsx
  src/components/writepage/WritePagePosition.tsx
  src/components/writepage/mobile/MobileInput.tsx
  src/components/writepage/mobile/WritePageMobileBody.tsx
  src/components/writepage/mobile/WritePageMobileFooter.tsx
  src/components/writepage/mobile/WritePageMobilePosition.tsx
  src/components/writepage/mobile/WritePageMobileThumbnail.tsx
Labels: enhancement

#241 [fix] 로그인/로그아웃 시 렌더링 버그 수정
  src/components/login/Welcome.tsx
  src/components/login/mobile/MobileWelcome.tsx
  src/components/mypage/LeftTab.tsx
  src/hooks/useHeader.ts
  src/hooks/useSocialLogin.ts
  src/hooks/useUpdateProfile.ts
Labels: bug

#242 [design] 모바일 메인페이지 UI 수정
  src/components/MobileContentCard.tsx
  src/components/ScrollToTopButton.tsx
  src/components/findproject/mobile/FindProjectMobileList.tsx
  src/components/main/findUsers/FindUserSlider.tsx
  src/components/main/findUsers/MobileFindUserSlider.tsx
  src/components/main/findUsers/MobileMainFindUsers.tsx
  src/components/main/recommendation/MobileMainRecommendation.tsx
  src/components/mypage/mobile/MobileProjectList.tsx
  src/components/projectDetail/MemberInfoArea.tsx
  src/components/projectDetail/WriterToShareArea.tsx
  src/hooks/useSocialLogin.ts
  src/pages/MainPage.tsx
Labels: enhancement

#246 [fix] 글 작성 연속 클릭시 2번 작성되는 현상 수정
  src/components/common/mobile/MobileConfirmAlert.tsx
  src/hooks/useEditBoard.ts
  src/hooks/useWrite.ts
  src/pages/ProjectWritePage.tsx
Labels: bug

#250 [fix] 모바일 푸터 styled-components 오류 수정
  src/components/MobileFooter.tsx
Labels: bug

#249 [feat] 캘린더 데이터가 없을 때 nodata 문구 표시
  src/components/main/Calendar/ProjectList.tsx
Labels: enhancement

#254 [fix] 모바일 프로젝트 상세보기 UI 수정, 링크 추가
  src/components/projectDetail/mobile/MobileWirterToProjectInfoArea.tsx
  src/components/projectDetail/mobile/MobileWriterToProjectInfoArea.tsx
  src/components/projectDetail/mobile/projectDetailMobile.tsx
Labels: enhancement

#257 [feat] 모바일 상세보기 Viewer, 제목 ellipsis 적용
  src/components/ContentCard.tsx
  src/components/MobileContentCard.tsx
  src/components/common/mobile/MobileContainer.tsx
  src/components/main/Calendar/ProjectDetail.tsx
  src/components/main/Calendar/ProjectList.tsx
  src/components/projectDetail/mobile/MobileRecruitContentArea.tsx
  src/components/writepage/mobile/WritePageMobileFooter.tsx
  src/components/writepage/mobile/WritePageMobileHeader.tsx
  src/components/writepage/mobile/WritePageMobileThumbnail.tsx
Labels: enhancement

#259 [fix] 디테일 페이지 toast ui editor 수정시 바로 값 안바뀌는 버그 수정
  src/components/projectDetail/ContentArea.tsx
  src/components/projectDetail/mobile/MobileRecruitContentArea.tsx
Labels: bug

#264 [feat] 썸네일 기본 이미지 수정 및 버그 수정
  public/index.html
  src/assets/images/thumbnail_big.jpg
  src/assets/images/thumbnail_mobile.jpg
  src/assets/images/thumbnail_small.jpg
  src/components/ContentCard.tsx
  src/components/MobileContentCard.tsx
  src/components/common/myProjectList/ProjectItem.tsx
  src/components/findproject/FindProjectHeader.tsx
  src/components/projectDetail/TitleThumbnailArea.tsx
  src/pages/FindProjectPage.tsx
Labels: bug, enhancement

#266 [PR] 마이페이지, 공개프로필에서 사용하는 프로젝트 카드 오류 해결
  src/apis/mypageUsers.ts
  src/apis/postDetail.ts
  src/components/common/myProjectList/ProjectList.tsx
  src/components/projectDetail/TitleThumbnailArea.tsx
  src/components/projectDetail/mobile/ModifyDeleteDropDown.tsx
  src/pages/ProjectDetailPage.tsx
  src/utils/staleTime.ts
Labels: bug

#267 [fix] 푸터 UI, 버그 수정
  src/assets/images/footer_gmail.png
  src/components/Footer.tsx
  src/components/MobileFooter.tsx
  src/components/common/mobile/MobileContainer.tsx
  src/components/findproject/FindProjectHeader.tsx
  src/components/main/recommendation/MobileMainRecommendation.tsx
  src/components/mypage/LeftTab.tsx
  src/components/mypage/mobile/MobileMyPage.tsx
  src/components/mypage/mobile/MobileProjectList.tsx
  src/components/mypage/mobile/MobileUserInfo.tsx
  src/pages/MainPage.tsx
  src/pages/ProjectEditPage.tsx
Labels: bug, enhancement

#271 [feat] 파비콘 추가
  public/favicon.ico
  public/favicon/android-chrome-192x192.png
  public/favicon/android-chrome-512x512.png
  public/favicon/apple-touch-icon.png
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon.ico
  public/favicon/site.webmanifest
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
Labels: enhancement

#274 [PR] 마이페이지, 공개프로필 undefined 오류 수정
  src/assets/images/404ErrorImg.png
  src/assets/images/404ErrorMessage.png
  src/components/common/myProjectList/ProjectList.tsx
  src/components/mypage/mobile/MobileProjectList.tsx
  src/hooks/useProjectList.ts
  src/pages/ErrorPage.tsx
  src/routes/Router.tsx
Labels: bug, enhancement

#275 [feat] 회원탈퇴 기능 구현
  src/apis/userService.ts
  src/components/main/findUsers/FindUserSlider.tsx
  src/components/main/findUsers/MobileFindUserSlider.tsx
  src/components/mypage/LeftTab.tsx
  src/components/popup/CustomButton.tsx
  src/components/popup/ReadInboxNote.tsx
  src/components/popup/mobile/MobileCustomButton.tsx
  src/components/popup/mobile/MobileReadInboxNote.tsx
  src/hooks/useSocialLogin.ts
  src/pages/PublicProfilePage.tsx
  src/react-app-env.d.ts
Labels: enhancement

#280 [PR] 현재 참여 중인 인원 분리, 마우스오버 효과 추가
  src/components/projectDetail/ApplicantCard.tsx
  src/components/projectDetail/ApplyModal/ApplyButtonArea.tsx
  src/components/projectDetail/ApplyModal/ApplyModal.tsx
  src/components/projectDetail/ApplyModal/ApplyMotiveArea.tsx
  src/components/projectDetail/ApplyModal/ApplyPositonArea.tsx
  src/components/projectDetail/ContentArea.tsx
  src/components/projectDetail/InviteModals/InviteModal.tsx
  src/components/projectDetail/MemberInfoArea.tsx
  src/components/projectDetail/ProjectInfoArea.tsx
  src/components/projectDetail/Share.tsx
  src/components/projectDetail/WriterToShareArea.tsx
  src/components/projectDetail/mobile/MobileApplicantCard.tsx
  src/components/projectDetail/mobile/MobileApplicantsList.tsx
  src/components/projectDetail/mobile/MobileMemberInfoArea.tsx
  src/components/projectDetail/mobile/MobileModal/MobileInviteModal.tsx
  src/components/projectDetail/mobile/MobileRecruitContentArea.tsx
  src/components/projectDetail/mobile/MobileTitleThumbnailArea.tsx
  src/components/projectDetail/mobile/MobileViewsToShareArea.tsx
  src/components/projectDetail/mobile/MobileWirterToProjectInfoArea.tsx
  src/components/projectDetail/mobile/ModifyDeleteDropDown.tsx
  src/components/publicProfile/UserPositions.tsx
  src/components/publicProfile/UserStacks.tsx
  src/components/publicProfile/mobile/MobilePublicProfilePage.tsx
  src/components/publicProfile/mobile/PublicProfileImage.tsx
  src/pages/MainPage.tsx
  src/pages/ProjectDetailPage.tsx
Labels: enhancement

#282 [PR] 초대하기 모달 수정
  src/components/projectDetail/ApplyModal/ApplyModal.tsx
  src/components/projectDetail/InviteModals/InviteModal.tsx
  src/components/projectDetail/mobile/MobileModal/MobileInviteModal.tsx
  src/pages/MainPage.tsx
Labels: enhancement

#284 fix: 불필요한 로그 삭제
  src/components/mypage/mobile/MobileProjectList.tsx
Labels: enhancement

#285 Detto v1.1.1
  src/components/mypage/mobile/MobileProjectList.tsx
Labels: enhancement

#286 [fix] 마이페이지 프로젝트 리스트 조회 수정
  src/components/common/myProjectList/ProjectList.tsx
  src/components/mypage/mobile/MobileProjectList.tsx
Labels: bug

#288 [feat] 프로젝트 찾기 Card 좋아요 기능 추가 및 애니메이션 효과
  src/apis/boardService.ts
  src/apis/userService.ts
  src/components/ContentCard.tsx
  src/components/MobileContentCard.tsx
  src/hooks/useFindProject.ts
Labels: enhancement

#289 [feat] 글 작성 & 수정 디자인 수정 및 에러 해결
  src/components/ContentCard.tsx
  src/components/MobileContentCard.tsx
  src/components/editpage/ProjectEditPageBody.tsx
  src/components/editpage/ProjectEditPageFooter.tsx
  src/components/editpage/mobile/EditPageMobileFooter.tsx
  src/components/editpage/mobile/EditPageMobileThumbnail.tsx
  src/components/writepage/ProjectWritePageBody.tsx
  src/components/writepage/mobile/WritePageMobileFooter.tsx
  src/components/writepage/mobile/WritePageMobileThumbnail.tsx
Labels: bug

#290 [feat] 프리뷰 버그
  src/components/ContentCard.tsx
  src/components/MobileContentCard.tsx
Labels: bug

#293 [PR] 공개프로필 에러 수정
  src/components/common/myProjectList/ProjectList.tsx
  src/components/main/Calendar/MainCalendar.tsx
  src/components/mypage/mobile/MobileProjectList.tsx
  src/components/projectDetail/TitleThumbnailArea.tsx
  src/components/projectDetail/mobile/MobileApplicantCard.tsx
  src/components/projectDetail/mobile/MobileApplicantsList.tsx
Labels: bug, enhancement

#296 [feat] 상세보기 페이지, 에러 페이지 메타태그 적용
  src/pages/ErrorPage.tsx
  src/pages/ProjectDetailPage.tsx
Labels: enhancement

#298 [fix] 썸네일이 존재하지 않을 때 메타태그 수정
  src/pages/ProjectDetailPage.tsx
Labels: bug

#300 [feat] 글 작성 & 수정 메타태그 추가
  src/assets/images/logo_main2.gif
  src/pages/ProjectEditPage.tsx
  src/pages/ProjectWritePage.tsx
Labels: enhancement

#301 [공통] 이미지 삭제 시 기본이미지 들어가도록 변경
  src/hooks/useProfileImage.ts
Labels: bug

#303 [feat] 랜딩페이지 SEO 추가
  README.md
  public/index.html
  src/pages/ErrorPage.tsx
  src/pages/FindProjectPage.tsx
  src/pages/MainPage.tsx
  src/pages/MyPage.tsx
  src/pages/ProjectDetailPage.tsx
  src/pages/ProjectEditPage.tsx
  src/pages/ProjectWritePage.tsx
  src/pages/PublicProfilePage.tsx
Labels: enhancement

#306 [feat] 마이페이지, 헤더, 푸터 amplitude 기능 추가
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/MobileHeader.tsx
  src/components/mypage/MyPageInfo.tsx
  src/components/mypage/mobile/MobileUserInfo.tsx
  src/components/popup/mobile/MobileDropdownMenu.tsx
  src/hooks/useProjectList.ts
Labels: enhancement

#307 [fix] 유효성 검사 실패 시 버튼 disabled되는 에러 수정
  src/components/popup/ReplyNote.tsx
  src/components/popup/SendNote.tsx
Labels: bug

#308 [feat] 팀원찾기, 글 작성&수정 Amplitude 적용
  src/components/ContentCard.tsx
  src/components/MobileContentCard.tsx
  src/hooks/useEditBoard.ts
  src/hooks/useFindProject.ts
  src/hooks/useWrite.ts
  src/pages/FindProjectPage.tsx
Labels: enhancement

#309 [feat] 소셜로그인, 쪽지/알림 버튼 클릭 이벤트 로깅
  src/components/Header.tsx
  src/components/popup/NoteMessage.tsx
  src/components/popup/NotificationMessage.tsx
  src/components/popup/ReplyNote.tsx
  src/components/popup/SendNote.tsx
  src/hooks/useSocialLogin.ts
  src/utils/amplitude.ts
Labels: enhancement

#310 [feat] 로딩 로고 변경
  public/videos/logo_loading.webm
  src/pages/LoadingPage.tsx
Labels: enhancement

#311 [feat]메인페이지 Amplitude 코드 추가
  src/components/main/Calendar/ProjectDetail.tsx
  src/components/main/findUsers/FindUserSlider.tsx
  src/components/main/findUsers/MobileFindUserSlider.tsx
  src/components/main/recommendation/MainRecommendation.tsx
  src/components/main/recommendation/MobileMainRecommendation.tsx
Labels: enhancement

#313 [feat] 메인페이지 Title Helmet 적용
  src/pages/MainPage.tsx
Labels: enhancement

#312 [PR] 프로젝트 상세페이지, 공개프로필 Amplitude 적용
  src/components/projectDetail/ApplyModal/ApplyButtonArea.tsx
  src/components/projectDetail/InviteModals/InviteModal.tsx
  src/components/projectDetail/Likes.tsx
  src/components/projectDetail/MemberInfoArea.tsx
  src/components/projectDetail/Share.tsx
  src/components/projectDetail/TitleThumbnailArea.tsx
  src/components/projectDetail/WriterToShareArea.tsx
  src/components/projectDetail/mobile/MobileMemberInfoArea.tsx
  src/components/projectDetail/mobile/MobileModal/MobileInviteModal.tsx
  src/components/projectDetail/mobile/MobileWirterToProjectInfoArea.tsx
  src/components/projectDetail/mobile/ModifyDeleteDropDown.tsx
  src/pages/ProjectDetailPage.tsx
  src/pages/PublicProfilePage.tsx
  src/utils/amplitude.ts
Labels: enhancement

#315 [refactor] 쪽지/알림 커스텀훅 리팩토링
  src/components/common/ApplyButtonArea.tsx
  src/components/popup/ReplyNote.tsx
  src/components/popup/SendNote.tsx
  src/components/popup/mobile/MobileReplyNote.tsx
  src/components/popup/mobile/MobileSendNote.tsx
  src/components/projectDetail/ApplyModal/ApplyButtonArea.tsx
  src/components/projectDetail/InviteModals/InviteModal.tsx
  src/hooks/useNote.ts
  src/hooks/useNotification.ts
  src/pages/ProjectDetailPage.tsx
Labels: enhancement

#316 [design] 로그인/회원가입 모달 UI 수정
  src/assets/images/login_facebook.png
  src/assets/images/login_github.png
  src/assets/images/login_google.png
  src/assets/images/login_key.png
  src/assets/images/login_logo.webp
  src/assets/images/login_mobile_facebook.png
  src/assets/images/login_mobile_github.png
  src/assets/images/login_mobile_google.png
  src/components/common/modal/ModalContainer.tsx
  src/components/login/LoginModal.tsx
  src/components/login/SetPositions.tsx
  src/components/login/SetProfile.tsx
  src/components/login/SetSkills.tsx
  src/components/login/SocialLogin.tsx
  src/components/login/Welcome.tsx
  src/components/login/mobile/MobileSocialLogin.tsx
  src/components/mypage/MyPageProfileImage.tsx
Labels: enhancement

#318 [feat] 스크롤투탑 버튼 클릭 이벤트 로깅
  src/components/ScrollToTopButton.tsx
Labels: enhancement
