Repository Team-Detto/Detto, pull requests merged in 2023-03, with the labels that each got.

#319 [PR] 프로젝트 상세페이지 디자인 수정
  src/components/projectDetail/ApplyButtonArea.tsx
  src/components/projectDetail/ApplyModal/ApplyModal.tsx
  src/components/projectDetail/ApplyModal/ApplyModalButtonArea.tsx
  src/components/projectDetail/ApplyModal/ApplyPositionArea.tsx
  src/components/projectDetail/InviteModals/InviteModal.tsx
  src/components/projectDetail/Likes.tsx
  src/components/projectDetail/MemberInfoArea.tsx
  src/components/projectDetail/ProjectInfoArea.tsx
  src/components/projectDetail/Share.tsx
  src/components/projectDetail/TitleThumbnailArea.tsx
  src/components/projectDetail/WriterToShareArea.tsx
  src/pages/ProjectDetailPage.tsx
Labels: enhancement

#321 [fix] 헤더, 마이페이지 코드 개선
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/mypage/CareerRadioInput.tsx
  src/components/mypage/CheckboxButton.tsx
  src/components/mypage/MyPageInfo.tsx
  src/components/mypage/mobile/MobileUserInfo.tsx
  src/components/popup/mobile/MobileDropdownMenu.tsx
  src/hooks/index.ts
  src/hooks/useGradient.ts
  src/hooks/useHeader.ts
Labels: bug, enhancement

#323 [design] 회원가입 UI 수정사항 반영
  src/components/common/SkillButton.tsx
  src/components/login/ConfirmButton.tsx
  src/components/login/SetPositions.tsx
  src/components/login/SetProfile.tsx
  src/components/login/SetSkills.tsx
  src/components/login/SetSkillsPageStack.tsx
  src/components/login/mobile/MobileSetProfile.tsx
  src/components/writepage/WritePageStack.tsx
Labels: enhancement

#324 [PR] 상세페이지 스택, 포지션 디자인 수정
  src/components/projectDetail/ProjectInfoArea.tsx
  src/components/projectDetail/TitleThumbnailArea.tsx
  src/components/projectDetail/mobile/ModifyDeleteDropDown.tsx
  src/pages/ProjectDetailPage.tsx
Labels: enhancement

#325 [feat] img 태그에 누락된 alt 추가
  src/components/ContentCard.tsx
  src/components/MobileContentCard.tsx
  src/components/main/banner/MainBanner.tsx
  src/components/main/banner/MobileMainBanner.tsx
  src/components/main/findUsers/FindUserSlider.tsx
  src/components/main/findUsers/MobileFindUserSlider.tsx
  src/components/popup/ReadInboxNote.tsx
  src/components/popup/ReadOutboxNote.tsx
  src/components/popup/ReplyNote.tsx
  src/components/popup/SendNote.tsx
  src/components/popup/mobile/MobileReadInboxNote.tsx
  src/components/popup/mobile/MobileReadOutboxNote.tsx
  src/components/popup/mobile/MobileReplyNote.tsx
  src/components/popup/mobile/MobileSendNote.tsx
  src/components/projectDetail/ApplicantCard.tsx
  src/components/projectDetail/InviteModals/InviteModal.tsx
  src/components/projectDetail/MemberInfoArea.tsx
  src/components/projectDetail/TitleThumbnailArea.tsx
  src/components/projectDetail/WriterToShareArea.tsx
  src/components/projectDetail/mobile/MobileApplicantCard.tsx
  src/components/projectDetail/mobile/MobileMemberInfoArea.tsx
  src/components/projectDetail/mobile/MobileTitleThumbnailArea.tsx
  src/components/projectDetail/mobile/MobileWirterToProjectInfoArea.tsx
  src/components/publicProfile/mobile/PublicProfileImage.tsx
  src/pages/ErrorPage.tsx
Labels: enhancement

#327 [fix] react query 에러 해결 & staleTime 조정
  src/components/ContentCard.tsx
  src/components/MobileContentCard.tsx
  src/components/projectDetail/ApplyModal/ApplyModal.tsx
  src/components/projectDetail/ApplyModal/ApplyModalButtonArea.tsx
  src/components/projectDetail/Likes.tsx
  src/components/projectDetail/Share.tsx
  src/hooks/useFindProject.ts
  src/index.tsx
  src/pages/MyPage.tsx
  src/pages/ProjectDetailPage.tsx
  src/pages/PublicProfilePage.tsx
  src/utils/staleTime.ts
Labels: bug, enhancement

#330 feat: React Query Devtools 추가
  .pnp.cjs
  .yarn/cache/@tanstack-match-sorter-utils-npm-8.7.6-2bff79c61d-3f3dda277e.zip
  .yarn/cache/@tanstack-react-query-devtools-npm-4.24.12-981c99b6e6-8cea2cd992.zip
  .yarn/cache/copy-anything-npm-3.0.3-a24d77ec4d-d456dc5ec9.zip
  .yarn/cache/is-what-npm-4.1.8-57bef8cfbc-b9bec3acff.zip
  .yarn/cache/remove-accents-npm-0.4.2-7cb341092a-84a6988555.zip
  .yarn/cache/superjson-npm-1.12.2-e37d205ed2-cf7735e172.zip
  package.json
  src/index.tsx
  yarn.lock
Labels: enhancement

#329 [fix] 마이페이지, 공개프로필 프로젝트 리스트 최신순 변경
  src/hooks/useProjectList.ts
Labels: enhancement

#332 [PR] 공개프로필, 상세페이지 모바일 디자인 수정
  src/components/common/myProjectList/ProjectsTab.tsx
  src/components/projectDetail/ProjectInfoArea.tsx
  src/components/projectDetail/mobile/MobileWirterToProjectInfoArea.tsx
  src/components/publicProfile/mobile/MobilePublicProfilePage.tsx
Labels: enhancement

#334 [refactor] js tree shaking & image resize
  src/apis/getPost.ts
  src/apis/mypageUsers.ts
  src/apis/notes.ts
  src/apis/notifications.ts
  src/apis/userService.ts
  src/assets/images/404ErrorImg.png
  src/assets/images/404ErrorImg.webp
  src/assets/images/404ErrorMessage.png
  src/assets/images/404ErrorMessage.webp
  src/assets/images/detoLogo.png
  src/assets/images/login_welcome.png
  src/assets/images/login_welcome.webp
  src/assets/images/logo_main1.png
  src/assets/images/logo_main1.webp
  src/assets/images/mobileFirstBanner.png
  src/assets/images/mobileFirstBanner.webp
  src/assets/images/mobilesecondBanner.png
  src/assets/images/mobilesecondBanner.webp
  src/assets/images/scroll_to_top.png
  src/assets/images/scroll_to_top.webp
  src/assets/images/thumbnail_big.jpg
  src/assets/images/thumbnail_big.webp
  src/assets/images/thumbnail_mobile.jpg
  src/assets/images/thumbnail_mobile.png
  src/assets/images/thumbnail_small.jpg
  src/assets/images/thumbnail_small.webp
  src/components/ContentCard.tsx
  src/components/MobileContentCard.tsx
  src/components/MobileHeader.tsx
  src/components/ScrollToTopButton.tsx
  src/components/common/myProjectList/ProjectItem.tsx
  src/components/login/SetPositions.tsx
  src/components/login/Welcome.tsx
  src/components/login/mobile/MobileSetPositions.tsx
  src/components/login/mobile/MobileSetProfile.tsx
  src/components/login/mobile/MobileSetSkillsPageStack.tsx
  src/components/login/mobile/MobileWelcome.tsx
  src/components/main/Calendar/MainCalendar.tsx
  src/components/main/Calendar/ProjectCalendar.tsx
  src/components/main/banner/MainBanner.tsx
  src/components/main/banner/MobileMainBanner.tsx
  src/components/mypage/LeftTab.tsx
  src/components/popup/NoteBox.tsx
  src/components/popup/mobile/MobileNoteBox.tsx
  src/components/projectDetail/InviteModals/InviteModal.tsx
  src/components/projectDetail/TitleThumbnailArea.tsx
  src/components/projectDetail/Views.tsx
  src/components/projectDetail/WriterToShareArea.tsx
  src/components/projectDetail/mobile/MobileApplicantCard.tsx
  src/components/projectDetail/mobile/MobileViewsToShareArea.tsx
  src/components/publicProfile/UserPositions.tsx
  src/components/publicProfile/mobile/MobilePublicProfilePage.tsx
  src/hooks/useProjectList.ts
  src/pages/ErrorPage.tsx
  src/pages/ProjectDetailPage.tsx
  src/routes/Router.tsx
  src/utils/amplitude.ts
Labels: enhancement

#337 [fix] 마이페이지 프로젝트 아이템 버그 수정, 헤더 네비바 수정
  src/components/Header.tsx
  src/components/common/myProjectList/ProjectList.tsx
  src/components/popup/mobile/MobileDropdownMenu.tsx
  src/pages/FindProjectPage.tsx
Labels: bug, enhancement

#338 [fix] 모바일 프로젝트 상세보기 디자인 수정
  src/components/projectDetail/mobile/MobileTitleThumbnailArea.tsx
Labels: bug

#339 [feat] 접근성 개선을 위한 태그 수정
  src/components/ContentCard.tsx
  src/components/findproject/FindProjectHeader.tsx
  src/components/projectDetail/Likes.tsx
  src/components/projectDetail/ProjectInfoArea.tsx
  src/components/writepage/ProjectWritePageBody.tsx
Labels: enhancement

#340 [PR] 새 게시글 작성 후 작성한 글 목록에 업데이트 되지 않는 오류 수정
  src/components/common/myProjectList/ProjectList.tsx
  src/components/projectDetail/Likes.tsx
  src/components/projectDetail/ProjectInfoArea.tsx
  src/components/projectDetail/mobile/MobileWirterToProjectInfoArea.tsx
Labels: bug, enhancement

#342 [PR] 프로젝트 상세페이지, 공개페이지 컴포넌트, 훅 분리
  src/components/publicProfile/UserProfileBox.tsx
  src/hooks/useDetailProject.ts
  src/hooks/usePublicProfile.ts
  src/pages/ProjectDetailPage.tsx
  src/pages/PublicProfilePage.tsx
Labels: enhancement

#343 [refactor] 로그인/회원가입, 알림/쪽지 커스텀훅 추가
  src/components/login/SetPositions.tsx
  src/components/login/SetSkills.tsx
  src/components/login/mobile/MobileSetPositions.tsx
  src/components/login/mobile/MobileSetSkills.tsx
  src/components/popup/NoteMessage.tsx
  src/components/popup/NotificationMessage.tsx
  src/hooks/useNoteMessage.ts
  src/hooks/useNotificationMessage.ts
  src/hooks/useSetPositions.ts
  src/hooks/useSetSkills.ts
Labels: enhancement

#344 [PR] 글 삭제시 발생하는 버그 수정
  src/components/common/mobile/MobileAlert.tsx
  src/components/projectDetail/Likes.tsx
  src/components/writepage/mobile/WritePageMobileThumbnail.tsx
Labels: bug

#347 [PR] 포지션 버그 수정
  src/components/projectDetail/ProjectInfoArea.tsx
  src/components/projectDetail/mobile/MobileWirterToProjectInfoArea.tsx
Labels: bug

#349 [fix] 글 작성 수정시 포지션 선택 두자릿수 이상 선택 못하게 적용
  src/utils/validation.ts
Labels: bug

#350 fix: setTimeout 삭제
  src/apis/postDetail.ts
  src/components/projectDetail/Likes.tsx
Labels: bug

#361 [fix] Content Card 좋아요 클릭시 query invalidate 처리
  src/components/ContentCard.tsx
  src/components/MobileContentCard.tsx
Labels: bug

#362 [fix] 디테일 페이지에서 좋아요 클릭시 Content Card에 반영 안되는 현상 수정
  src/components/projectDetail/Likes.tsx
Labels: bug

#366 [fix] 보낸 쪽지함에서 받는 사람 닉네임을 표시
  src/components/popup/NoteMessage.tsx
  src/hooks/useNoteMessage.ts
Labels: bug

#359 [PR] 모바일 게시글 작성시 마이페이지 업데이트 오류
  src/components/mypage/mobile/MobileProjectList.tsx
Labels: bug

#365 [fix] 모달창이 열릴 때 헤더 배경이 투명해지는 버그 해결
  src/components/common/Alert.tsx
  src/components/common/ConfirmAlert.tsx
  src/components/common/mobile/MobileAlert.tsx
  src/components/login/LoginModal.tsx
  src/components/mypage/ProfileImageModal.tsx
  src/components/popup/NoteModal.tsx
  src/components/projectDetail/ApplicantCard.tsx
  src/components/projectDetail/ApplyModal/ApplyModal.tsx
  src/utils/modal.ts
Labels: bug

#367 [PR] 프로젝트 상세보기 페이지 유저 피드백 반영#1
  src/components/common/ApplyPositionButton.tsx
  src/components/projectDetail/ApplyModal/ApplyModal.tsx
  src/components/projectDetail/ApplyModal/ApplyPositionArea.tsx
  src/components/projectDetail/MemberInfoArea.tsx
  src/components/projectDetail/ProjectInfoArea.tsx
  src/components/projectDetail/mobile/MobileApplyButtonArea.tsx
  src/components/projectDetail/mobile/MobileMemberInfoArea.tsx
  src/components/projectDetail/mobile/MobileWirterToProjectInfoArea.tsx
  src/components/projectDetail/mobile/projectDetailMobile.tsx
  src/pages/ProjectDetailPage.tsx
  src/utils/positions.ts
Labels: enhancement

#370 [feat] 팀원 찾기 페이지 카드 좋아요 클릭시 카운트 바로 반영 되도록 변경
  src/apis/boardService.ts
  src/components/ContentCard.tsx
  src/components/MobileContentCard.tsx
  src/components/findproject/FindProjectList.tsx
  src/components/findproject/mobile/FindProjectMobileList.tsx
  src/hooks/useFindProject.ts
  src/pages/FindProjectPage.tsx
Labels: bug

#371 [fix] 인풋태그 클리어 버튼 버그, placeholder 수정
  src/components/mypage/TextInput.tsx
  src/components/mypage/mobile/MobileTopTab.tsx
  src/components/mypage/mobile/MobileUserInfo.tsx
  src/hooks/useUpdateProfile.ts
Labels: bug

#377 [PR] 프로젝트 상세페이지 마감일 추가
  src/components/projectDetail/ProjectInfoArea.tsx
Labels: enhancement

#378 [feat] 500~1200px 반응형 디자인
  src/components/editpage/mobile/EditPageMobileBody.tsx
  src/components/editpage/mobile/EditPageMobileDeadline.tsx
  src/components/editpage/mobile/EditPageMobileFooter.tsx
  src/components/editpage/mobile/EditPageMobileHeader.tsx
  src/components/editpage/mobile/EditPageMobilePeriod.tsx
  src/components/editpage/mobile/EditPageMobileThumbnail.tsx
  src/components/main/banner/MobileMainBanner.tsx
  src/components/projectDetail/mobile/MobileMemberInfoArea.tsx
  src/components/projectDetail/mobile/MobileTitleThumbnailArea.tsx
  src/components/projectDetail/mobile/MobileViewsToShareArea.tsx
  src/components/projectDetail/mobile/MobileWirterToProjectInfoArea.tsx
  src/components/writepage/mobile/WritePageMobileBody.tsx
  src/components/writepage/mobile/WritePageMobileDeadline.tsx
  src/components/writepage/mobile/WritePageMobileFooter.tsx
  src/components/writepage/mobile/WritePageMobileHeader.tsx
  src/components/writepage/mobile/WritePageMobilePeriod.tsx
  src/components/writepage/mobile/WritePageMobileThumbnail.tsx
  src/hooks/useIsMobile.ts
  src/pages/FindProjectPage.tsx
Labels: enhancement

#381 [fix] 모집중 문구 변경 & 무한 스크롤 버그 수정
  src/apis/boardService.ts
  src/components/findproject/FindProjectHeader.tsx
  src/components/findproject/mobile/FindProjectMobileHeader.tsx
Labels: bug

#382 [PR] 콘텐츠 카드 오른쪽 상단 마감 D-day 띄우기
  src/components/ContentCard.tsx
  src/components/MobileContentCard.tsx
  src/utils/date.ts
Labels: enhancement

#386 [PR] 마감된 게시글 마감일 수정 못하도록 수정
  src/components/common/ApplyPositionButton.tsx
  src/components/editpage/EditPageDeadline.tsx
  src/components/editpage/EditPageStack.tsx
  src/components/editpage/ProjectEditPageBody.tsx
  src/components/projectDetail/MemberInfoArea.tsx
Labels: enhancement

#387 [feat] 모바일 마이페이지 회원탈퇴 추가
  src/components/mypage/LeftTab.tsx
  src/components/mypage/TextInput.tsx
  src/components/mypage/mobile/MobileUserInfo.tsx
  src/hooks/index.ts
  src/hooks/useWithdrawal.ts
Labels: enhancement

#389 [feat] 날짜를 변경하면 프로젝트 리스트 슬라이더를 첫번째 페이지로 이동
  src/components/main/Calendar/ProjectList.tsx
Labels: enhancement

#388 [feat] 모바일 상세페이지 모집마감일 추가
  src/components/projectDetail/ProjectInfoArea.tsx
  src/components/projectDetail/mobile/MobileWirterToProjectInfoArea.tsx
Labels: enhancement

#392 [PR] 지원자목록 슬라이드로 수정
  src/components/ContentCard.tsx
  src/components/MobileContentCard.tsx
  src/components/projectDetail/ApplicantCard.tsx
  src/components/projectDetail/ApplicantListArea.tsx
Labels: enhancement

#394 [design] 프로젝트 상세보기 에디터 CSS 수정
  src/components/projectDetail/ContentArea.tsx
  src/components/projectDetail/mobile/MobileRecruitContentArea.tsx
Labels: enhancement

#393 [PR] 닉네임 호버기능 삭제
  src/components/projectDetail/MemberInfoArea.tsx
Labels: enhancement

#396 [feat] 카카오톡 공유하기 기능 추가
  public/index.html
  src/assets/images/share_kakao.png
  src/components/Footer.tsx
  src/components/MobileFooter.tsx
  src/components/projectDetail/Share.tsx
  src/components/projectDetail/WriterToShareArea.tsx
  src/components/projectDetail/mobile/MobileViewsToShareArea.tsx
  src/pages/ProjectDetailPage.tsx
  src/react-app-env.d.ts
Labels: enhancement

#398 [fix] 에디터 툴바 렌더링이 안되는 에러 수정
  src/components/TextEditor.tsx
Labels: bug

#399 [fix] 카카오톡 공유 이미지, 모바일 위치 수정
  src/assets/images/share_kakao.png
  src/components/projectDetail/Share.tsx
Labels: bug

#401 [PR] 자동 마감 안될 경우 D-day 예외처리
  src/components/ContentCard.tsx
  src/components/projectDetail/MemberInfoArea.tsx
Labels: enhancement

#404 [feat] 프로젝트 글 작성/수정 페이지 에디터 CSS 수정
  src/components/TextEditor.tsx
  src/components/projectDetail/ContentArea.tsx
  src/components/projectDetail/mobile/MobileRecruitContentArea.tsx
  src/components/writepage/ProjectWritePageFooter.tsx
  src/components/writepage/mobile/WritePageMobileFooter.tsx
Labels: enhancement

#405 [rename] 비디오 파일 위치 이동
  src/assets/videos/logo_loading.webm
  src/assets/videos/logo_main2.webm
  src/components/main/banner/MainBanner.tsx
  src/components/projectDetail/ContentArea.tsx
  src/pages/LoadingPage.tsx
Labels: enhancement

#407 [feat] 프로젝트 상세보기, 공개프로필 페이지의 query에 suspense 적용
  src/components/main/banner/MainBanner.tsx
  src/hooks/useDetailProject.ts
  src/hooks/usePublicProfile.ts
Labels: enhancement

#408 [fix] 팀원찾기 페이지 query suspense 추가
  src/assets/styles/globalStyled.ts
  src/hooks/useFindProject.ts
Labels: bug

#410 [PR] 좋아요 로직 수정, 초대하기 모달 슬라이드에서 발생하는 버그 수정
  src/components/projectDetail/ApplicantCard.tsx
  src/components/projectDetail/ApplicantListArea.tsx
  src/components/projectDetail/InviteModals/InviteModal.tsx
  src/components/projectDetail/Likes.tsx
Labels: bug, enhancement

#411 [fix] 유효성 검사 전 텍스트 trim
  src/hooks/useEditBoard.ts
  src/hooks/useNote.ts
  src/hooks/useUpdateProfile.ts
  src/hooks/useWrite.ts
Labels: bug

#413 [fix] 마이페이지 커서 버그
  src/components/common/myProjectList/ProjectItem.tsx
  src/components/common/myProjectList/mobile/MobileProjectListTab.tsx
  src/components/mypage/mobile/MobileTopTab.tsx
  src/components/mypage/mobile/MobileUserInfo.tsx
  src/components/publicProfile/UserStacks.tsx
  src/hooks/useUpdateProfile.ts
Labels: bug

#416 [feat] Sentry 설정 & Category 수정
  .pnp.cjs
  .yarn/cache/@sentry-browser-npm-7.41.0-12705ad960-27f403da4a.zip
  .yarn/cache/@sentry-core-npm-7.41.0-881041709c-59e80206e0.zip
  .yarn/cache/@sentry-react-npm-7.41.0-385c0aab1d-dc0e6f0a60.zip
  .yarn/cache/@sentry-replay-npm-7.41.0-7bad4671a9-4de5b6ab49.zip
  .yarn/cache/@sentry-tracing-npm-7.41.0-df2c129e00-4b537a408d.zip
  .yarn/cache/@sentry-types-npm-7.41.0-43c4c19240-d65c81770a.zip
  .yarn/cache/@sentry-utils-npm-7.41.0-2a536c0c8e-540d9f862c.zip
  package.json
  src/apis/boardService.ts
  src/apis/mypageUsers.ts
  src/apis/postDetail.ts
  src/hooks/useFindProject.ts
  src/hooks/useSocialLogin.ts
  src/hooks/useWithdrawal.ts
  src/index.tsx
  src/recoil/atoms.ts
  yarn.lock
Labels: bug, enhancement

#419 [PR] 지원하기 모달 제출 시 수정 안됨 고지, 공개프로필 탭버튼 디자인 수정
  src/components/common/myProjectList/ProjectsTab.tsx
  src/components/mypage/mobile/MobileProjectList.tsx
  src/components/projectDetail/ApplyModal/ApplyModal.tsx
  src/components/projectDetail/ApplyModal/ApplyModalButtonArea.tsx
  src/components/projectDetail/ApplyModal/ApplyMotiveArea.tsx
  src/components/projectDetail/mobile/MobileModal/MobileApplyModal.tsx
  src/components/projectDetail/mobile/projectDetailMobile.tsx
  src/hooks/useApply.ts
  src/pages/ProjectDetailPage.tsx
Labels: enhancement

#425 [PR] 마감시간 변경, d-day 남은 일수 계산 함수 수정
  src/apis/boardService.ts
  src/components/writepage/WritePageDeadline.tsx
  src/utils/date.ts
Labels: enhancement

#427 [메인] (모바일)배너 이미지 , 리스트 모집중인것만 필더링
  src/assets/images/mobileFirstBanner.webp
  src/assets/images/mobilesecondBanner.webp
  src/components/main/Calendar/ProjectList.tsx
  src/components/main/findUsers/MobileMainFindUsers.tsx
  src/components/main/recommendation/MobileMainRecommendation.tsx
Labels: enhancement

#426 [fix] 메인페이지 배너 움직이지 않는 에러 수정
  src/components/main/banner/MainBanner.tsx
Labels: bug

#429 [PR] 프로필 변경 시 프로젝트 상세보기 페이지, 초대하기 모달, 공개프로필에 반영
  src/apis/boardService.ts
  src/apis/postDetail.ts
  src/components/common/myProjectList/ProjectItemMembers.tsx
  src/components/editpage/EditPageDeadline.tsx
  src/components/login/SetProfile.tsx
  src/components/projectDetail/ApplicantCard.tsx
  src/components/projectDetail/ApplicantListArea.tsx
  src/components/projectDetail/InviteModals/InviteModal.tsx
  src/components/projectDetail/MemberInfoArea.tsx
  src/components/projectDetail/ParticipantsProfile.tsx
  src/components/projectDetail/mobile/MobileApplicantCard.tsx
  src/components/projectDetail/mobile/MobileMemberInfoArea.tsx
  src/components/projectDetail/mobile/MobileModal/MobileInviteModal.tsx
  src/hooks/useApply.ts
  src/hooks/useDetailProject.ts
  src/hooks/useFindProject.ts
  src/hooks/usePublicProfile.ts
Labels: enhancement

#431 [feat] 메인페이지 랜덤 팀원 슬라이드 수정
  src/apis/userService.ts
  src/components/main/findUsers/FindUserSlider.tsx
  src/components/main/findUsers/MobileFindUserSlider.tsx
  src/utils/staleTime.ts
Labels: enhancement

#432 [PR] ContentCard에 좋아요 컴포넌트 적용
  src/components/ContentCard.tsx
  src/components/MobileContentCard.tsx
  src/components/findproject/FindProjectList.tsx
  src/components/findproject/mobile/FindProjectMobileList.tsx
  src/components/projectDetail/Likes.tsx
  src/components/projectDetail/WriterToShareArea.tsx
  src/components/projectDetail/mobile/MobileViewsToShareArea.tsx
  src/pages/FindProjectPage.tsx
Labels: enhancement

#434 feat: 랜덤 팀원 슬라이드 limit, staleTime 수정
  src/apis/userService.ts
  src/components/main/findUsers/FindUserSlider.tsx
  src/components/main/findUsers/MobileFindUserSlider.tsx
  src/utils/staleTime.ts
Labels: enhancement

#435 [PR] Sentry에서 모니터링된 타입 에러 수정
  src/components/findproject/FindProjectList.tsx
  src/components/projectDetail/mobile/MobileApplicantCard.tsx
Labels: bug

#436 [fix] 무한 스크롤 로직 변경 및 콘텐츠 카드 하트 수정
  src/apis/boardService.ts
  src/components/ContentCard.tsx
  src/components/MobileContentCard.tsx
  src/hooks/useFindProject.ts
Labels: bug, enhancement

#437 [fix] 모바일 배너 이미지 고해상도 변경, 이름 변경
  src/assets/images/mobileFirstBanner.webp
  src/assets/images/mobileSecondBanner.webp
  src/assets/images/mobilesecondBanner.webp
  src/components/main/banner/MobileMainBanner.tsx
Labels: enhancement

#440 [fix] 상세보기 새로고침 시 하트, 작성자 공개프로필 링크 이동 이벤트 영역 수정
  src/apis/postDetail.ts
  src/components/projectDetail/Likes.tsx
  src/components/projectDetail/WriterToShareArea.tsx
  src/components/projectDetail/mobile/MobileWirterToProjectInfoArea.tsx
Labels: bug

#443 [fix] 콘텐츠 카드와 특정 디테일 게시판 버그 수정
  src/components/projectDetail/Likes.tsx
  src/components/projectDetail/mobile/MobileModal/MobileInviteModal.tsx
  src/hooks/useFindProject.ts
Labels: bug

#444 [PR] 상세 페이지 작성자 닉네임 옆 쪽지 아이콘 추가
  src/components/projectDetail/WriterToShareArea.tsx
  src/components/projectDetail/mobile/MobileWirterToProjectInfoArea.tsx
  src/components/publicProfile/mobile/PublicProfileImage.tsx
Labels: enhancement

#447 [feat] 글 작성 & 수정 뒤로가기 경고 알림 및 로딩 페이지 PC & Mobile 다른 스피너 적용
  src/assets/videos/logo_loading2.webm
  src/hooks/useEditBoard.ts
  src/hooks/useWrite.ts
  src/pages/LoadingPage.tsx
  src/pages/ProjectEditPage.tsx
  src/pages/ProjectWritePage.tsx
Labels: enhancement

#449 [docs] 리드미 업데이트
  README.md
Labels: documentation

#450 [feat] 글 작성 & 수정 새로고침시 경고 알람 문구 추가
  src/hooks/useEditBoard.ts
  src/hooks/useWrite.ts
Labels: enhancement

#448 [fix] calender 해당날의 프로젝트가 있으면 점찍기
  src/components/main/Calendar/ProjectCalendar.tsx
Labels: enhancement

#451 [fix] any 타입 일부 수정
  src/apis/findWithCollectionName.ts
  src/apis/mypageUsers.ts
  src/apis/notes.ts
  src/apis/postDetail.ts
  src/components/common/myProjectList/ProjectList.tsx
  src/components/main/Calendar/ProjectCalendar.tsx
  src/components/projectDetail/ApplicantCard.tsx
  src/utils/skills.ts
Labels: enhancement

#455 [PR] 삭제 시 이전페이지가 수정페이지이면 메인페이지로 보내도록 수정
  src/components/projectDetail/TitleThumbnailArea.tsx
  src/hooks/useEditBoard.ts
  src/pages/ProjectEditPage.tsx
  src/recoil/atoms.ts
Labels: bug

#456 [fix] any type 수정
  src/apis/findWithCollectionName.ts
  src/apis/mypageUsers.ts
  src/apis/notifications.ts
  src/components/projectDetail/Views.tsx
  src/hooks/useNote.ts
  src/hooks/useProfileImage.ts
  src/react-app-env.d.ts
  src/utils/amplitude.ts
Labels: enhancement

#457 [refactor] 로그인, 쪽지 모달 컴포넌트 리팩토링
  src/components/common/modal/GlobalModal.tsx
  src/components/common/modal/modalTypes.ts
  src/components/login/LoginModal.tsx
  src/components/login/SetPositions.tsx
  src/components/login/SetProfile.tsx
  src/components/login/SetSkills.tsx
  src/components/login/SocialLogin.tsx
  src/components/login/Welcome.tsx
  src/components/login/mobile/MobileSetPositions.tsx
  src/components/login/mobile/MobileSetProfile.tsx
  src/components/login/mobile/MobileSetSkills.tsx
  src/components/login/mobile/MobileSocialLogin.tsx
  src/components/login/mobile/MobileWelcome.tsx
  src/components/popup/NoteModal.tsx
  src/components/popup/ReadInboxNote.tsx
  src/components/popup/ReadOutboxNote.tsx
  src/components/popup/ReplyNote.tsx
  src/components/popup/SendNote.tsx
  src/components/popup/mobile/MobileReadInboxNote.tsx
  src/components/popup/mobile/MobileReadOutboxNote.tsx
  src/components/popup/mobile/MobileReplyNote.tsx
  src/components/popup/mobile/MobileSendNote.tsx
  src/components/projectDetail/InviteModals/InviteModal.tsx
  src/components/projectDetail/WriterToShareArea.tsx
  src/components/projectDetail/mobile/MobileWirterToProjectInfoArea.tsx
  src/components/publicProfile/mobile/PublicProfileImage.tsx
  src/hooks/useGlobalModal.ts
  src/hooks/usePublicProfile.ts
  src/pages/Root.tsx
  src/recoil/atoms.ts
Labels: enhancement

#458 [fix] 마이페이지 관련 로직 타입 추가 수정
  src/assets/images/footer_behance.png
  src/components/common/myProjectList/ProjectItemMembers.tsx
  src/components/common/myProjectList/ProjectList.tsx
  src/components/login/SetProfile.tsx
  src/components/main/recommendation/MobileMainRecommendation.tsx
  src/components/mypage/mobile/MobileProjectList.tsx
  src/hooks/useProfileImage.ts
  src/pages/MyPage.tsx
Labels: enhancement

#459 [fix] 컴포넌트 함수 선언식을 표현식으로 변경
  src/components/common/ScrollToTop.ts
  src/components/common/modal/GlobalModal.tsx
  src/components/common/modal/ModalNavigator.tsx
  src/components/login/ConfirmButton.tsx
  src/components/login/LoginModal.tsx
  src/components/login/SetPositions.tsx
  src/components/login/SetProfile.tsx
  src/components/login/SetSkills.tsx
  src/components/login/SetSkillsPageStack.tsx
  src/components/login/SocialLogin.tsx
  src/components/login/Welcome.tsx
  src/components/login/mobile/MobileConfirmButton.tsx
  src/components/login/mobile/MobileSetPositions.tsx
  src/components/login/mobile/MobileSetProfile.tsx
  src/components/login/mobile/MobileSetSkills.tsx
  src/components/login/mobile/MobileSetSkillsPageStack.tsx
  src/components/login/mobile/MobileSocialLogin.tsx
  src/components/login/mobile/MobileWelcome.tsx
  src/components/popup/CustomButton.tsx
  src/components/popup/NoteBox.tsx
  src/components/popup/NoteMessage.tsx
  src/components/popup/NotificationBox.tsx
  src/components/popup/NotificationMessage.tsx
  src/components/popup/PopupContainer.tsx
  src/components/popup/ReadInboxNote.tsx
  src/components/popup/ReadOutboxNote.tsx
  src/components/popup/ReplyNote.tsx
  src/components/popup/SendNote.tsx
  src/components/popup/mobile/MobileCustomButton.tsx
  src/components/popup/mobile/MobileNoteBox.tsx
  src/components/popup/mobile/MobileNotificationBox.tsx
  src/components/popup/mobile/MobileReadInboxNote.tsx
  src/components/popup/mobile/MobileReadOutboxNote.tsx
  src/components/popup/mobile/MobileReplyNote.tsx
  src/components/popup/mobile/MobileSendNote.tsx
  src/pages/Root.tsx
Labels: enhancement

#461 [feat] 모바일 에러 페이지 추가
  src/pages/ErrorPage.tsx
  src/pages/Root.tsx
  src/routes/Router.tsx
Labels: enhancement

#462 [fix] LoginModal 함수 선언식으로 변경
  src/components/login/LoginModal.tsx
Labels: bug

#464 fix: (모바일) 수정 후 삭제 시 발생하는 오류 예외처리
  src/components/projectDetail/TitleThumbnailArea.tsx
  src/components/projectDetail/mobile/ModifyDeleteDropDown.tsx
Labels: bug

#467 [docs] README 업데이트
  README.md
Labels: documentation

#468 [docs] README 디렉토리 구조 업데이트
  README.md
  src/apis/userService.ts
  src/components/main/findUsers/FindUserSlider.tsx
  src/components/main/findUsers/MobileFindUserSlider.tsx
  src/utils/staleTime.ts
Labels: documentation

#469 [docs] README 로고 변경
  README.md
Labels: documentation

#470 [fix] 지원자 정보 undefined 에러 수정
  src/components/projectDetail/ApplicantCard.tsx
  src/components/projectDetail/ApplicantListArea.tsx
  src/components/projectDetail/ApplyButtonArea.tsx
  src/components/projectDetail/InviteModals/InviteModal.tsx
  src/components/projectDetail/MemberInfoArea.tsx
  src/components/projectDetail/ParticipantsProfile.tsx
  src/components/projectDetail/mobile/MobileMemberInfoArea.tsx
  src/components/projectDetail/mobile/MobileModal/MobileInviteModal.tsx
  src/hooks/useNotification.ts
  src/react-app-env.d.ts
Labels: bug

#472 Detto 1.2.5
  src/components/ContentCard.tsx
  src/components/projectDetail/ApplicantCard.tsx
  src/components/projectDetail/ApplicantListArea.tsx
  src/components/projectDetail/ApplyButtonArea.tsx
  src/components/projectDetail/InviteModals/InviteModal.tsx
  src/components/projectDetail/MemberInfoArea.tsx
  src/components/projectDetail/ParticipantsProfile.tsx
  src/components/projectDetail/mobile/EndRecruitButton.tsx
  src/components/projectDetail/mobile/MobileMemberInfoArea.tsx
  src/components/projectDetail/mobile/MobileModal/MobileInviteModal.tsx
  src/hooks/useNotification.ts
  src/react-app-env.d.ts
Labels: version

#474 [PR] 좋아요 optimistic update로 수정
  src/components/projectDetail/Likes.tsx
Labels: enhancement
